name: new_flow

dependencies:
    - python==3.11
    - pip:
        - scipy
        - lxml
        - six
        - path.py
        - python-dateutil
        - pip
        - setuptools
        - plotly
        - gym
        - pyprind
        - nose2
        - cached_property
        - joblib
        - matplotlib
        - dill
        - lz4
        - setproctitle
        - psutil
        - opencv-python
        - boto3
        - numpy
        - pyglet
        - imutils
        - numpydoc
        - pandas
        - tabulate
        - awscli
        - torch
        - pytz
        - tensorboardX
        - gymnasium
        - dm_tree
        - pyarrow
        - ray
